let firstCard : Card = Card(color: Color.spades, value: Value.Ten)
let secondCard : Card = Card(color: Color.hearts, value: Value.King)
let thirdCard : Card = Card(color: Color.spades, value: Value.Ten)
let fourthCard : Card = Card(color: Color.diamonds, value: Value.Ace)
print("")
print("Override of variable test:")
print("First card is \(firstCard)")
print("Second card is \(secondCard)")
print("Third card is \(thirdCard)")
print("Fourth card is \(fourthCard)")
print("")
print("Override of function test:")
print("First card is equal to second card")
print(firstCard.isEqual(secondCard))
print("First card is equal to third card")
print(firstCard.isEqual(thirdCard))
print("First card is equal to fourth card")
print(firstCard.isEqual(fourthCard))
print("")
print("Overload of operator test:")
print("First card is equal to second card")
print(firstCard == secondCard)
print("First card is equal to third card")
print(firstCard == thirdCard)
print("First card is equal to fourth card")
print(firstCard == fourthCard)
